name: C/C++ CI

on:
  pull_request:
    paths:
      - 'docs/**'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - { name: Clang, cc: clang, cxx: clang++ }
          - { name: GNU, cc: gcc-10, cxx: g++-10 }
          - { name: Intel, cc: icx, cxx: icpx }
        build-mode: [Debug, Release]
    steps:
      - run: 'echo "No c++ formatting check required on docs changes"'
