name: C/C++ CI

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No c++ formatting check required on docs changes"'
