name: clang-format Check

on:
  pull_request:
    paths:
      - 'docs/**'
      - 'README.md'
jobs:
  formatting-check:
    name: C++ Formatting Check
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No c++ formatting check required on docs changes"'
