name: cmake-format check

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
  workflow_dispatch:
jobs:
  cmake-formatting-check:
    name: CMake Formatting Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Format CMake files
      id: cmake-format
      uses: Hespian/cmake-format-action@main
      with:
        args: --config-files .cmake-format.py --check
