name: cmake-format check

on:
  pull_request:
    paths:
      - 'docs/**'
      - 'README.md'
jobs:
  cmake-formatting-check:
    name: CMake Formatting Check
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required on docs changes"'
