name: Doxygen Check

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  doxygen-check:
    name: Doxygen Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: mattnotmitt/doxygen-action@v1.9.4
        with:
          doxyfile-path: 'docs/Doxyfile'
